#!/usr/bin/env Rscript
# Author: Gerson L Camillo
# Last rev: 20240907

## What does this do: extract PRP (total precipitation) variable from
#     NetCDF file that was generated by WRF and then:
#  - calculate difference between forecast and observed values
#  - calculate some statistics (BIAS, RMSE)
#  - save the results in CSV files

## Some important observations:
# 1. This script is configured for a **specific** grid configuration
#    used in WRF execution. The points **i** and **j** correspond to the
#    coordinates of the stations pre-configured in this script.
# 2. The WRF configuration domain used can be seen at these links:
#  https://github.com/glcamillo/model-wrf/tree/main/config-domains
#  https://github.com/glcamillo/model-wrf/blob/main/config-domains/r_sul-RS-SC-2d/projection.jpg
# 3. The 10 km AREA results in a 25 points around the station in the
#     Domain 2 of the output file from WRF (wrfout_d02_2015-07-24_00_00_00)
#     (domain configuration as pointed in 2.)

## Revisions:
#  v.1   20240321: initial: 25 grid points -> D2 -> 10km (area)
#  v.2   20240408: all stations will be calculated
#  v.2.5 20240411: all functionality working
#  v.2.6 20240530: bug correction: difference plotting
#  v.2.7 20240907: revision of the documentation

## How execute:
# 1. Set the executable bit:
#  $ chmod u+x wrfout-extract-PRP-with-R-for10kmAREA-and-statistics-from-D2.R
# 2. Execute with the next parameters (all in one line)
#  $ ./wrfout-extract-PRP-with-R-for10kmAREA-and-statistics-from-D2.R  
#        wrfout_d02_2020-08-14_00.nc
#        data-prp-pbl_BOUGEAULT-8-mp_MADWRF-96
#        ALL
#        24
#        AREA


## About the Arguments
# args[1]=wrfout_d02_2020-08-14_00.nc    NetCDF file from WRF output
# args[2]=data-prp-pbl_BOUGEAULT-8-mp_MADWRF-96        Name of output file (CSV data)
# args[3]=ALL            ALL for all meteorological stations (name or ALL)
# args[4]=24             Time of forecast (24,48, or 72 hours)
# args[5]=POINT|AREA     This script will extract only AREA for now


## About the stations
# - The argument for station can be: a) only one, or b) the code 'ALL'
#   ALL means the next stations:
# CH: Chapecó
# XA: Xanxerê
# JO: Joaçaba
# CN: Campos Novos
# CR: Curitibanos
# CA: Caçador

# 1. CH: Chapecó  -27.0853111  -52.6357111   679
#    WRF Grid points: -27.0789 j=236  -52.629 x=155
# 2. XA: Xanxerê -26.938666  -52.39809   878,74
#    WRF Grid points: -26.9241 j=243   -50.3976 i=167
# 3. JO: Joaçaba -27.16916666 -51.55888888  767,63
#    WRF Grid points: -27.1572 j=231   -51.5555 i=209
# 4. CN: Campos Novos -27.3886111 -51.21583333 963
#    WRF Grid points: -27.3935 j=218   -51.214  i=226
# 5. CT: Curitibanos  -27.288624 -50.604283 978,1
#    WRF Grid points: -27.2348 j=227   -50.5938 i=257
# 6. CA: Caçador   -26.819156  -50.98552   944,26m
#    WRF Grid points: -26.811  j=250    -50.992  x=238


# Times: ['2020-08-14T00:00:00.000000000' '2020-08-14T01:00:00.000000000'
# '2020-08-14T02:00:00.000000000' '2020-08-14T03:00:00.000000000'
# '2020-08-14T04:00:00.000000000' '2020-08-14T05:00:00.000000000'
# '2020-08-14T06:00:00.000000000' '2020-08-14T07:00:00.000000000'
# '2020-08-14T08:00:00.000000000' '2020-08-14T09:00:00.000000000'
# '2020-08-14T10:00:00.000000000' '2020-08-14T11:00:00.000000000'
# '2020-08-14T12:00:00.000000000' '2020-08-14T13:00:00.000000000'
# '2020-08-14T14:00:00.000000000' '2020-08-14T15:00:00.000000000'
# '2020-08-14T16:00:00.000000000' '2020-08-14T17:00:00.000000000'
# '2020-08-14T18:00:00.000000000' '2020-08-14T19:00:00.000000000'
# '2020-08-14T20:00:00.000000000' '2020-08-14T21:00:00.000000000'
# '2020-08-14T22:00:00.000000000' '2020-08-14T23:00:00.000000000'
# '2020-08-15T00:00:00.000000000']  Size: 25

## Observation about PRP variable
#  RAINC:description = "ACCUMULATED TOTAL CUMULUS PRECIPITATION" ;
#  RAINSH:description = "ACCUMULATED SHALLOW CUMULUS PRECIPITATION" ;
#  RAINNC:description = "ACCUMULATED TOTAL GRID SCALE PRECIPITATION" ;

# These variables accumulate forecast precipitation in each time steps

##  Some references about R and statistics
# Statistics from Package Metrics: generate unique values
# https://cran.r-project.org/web/packages/Metrics/Metrics.pdf
# ae (absolute error): output a vector with absolute differences
# mae, bias, rmse: summarization stats


########################################################
################# Processing: START ####################

library(ncdf4)
library(Metrics)
library(CFtime)  # Provide timestamp in POSIX formats

# For printing data e information
# DEBUG = TRUE
DEBUG = FALSE


# Print session info
if (DEBUG){
  version
  sessionInfo()
}

args <- commandArgs(trailingOnly = TRUE)
print(paste("args[1]:", args[1], "args[2]:", args[2],"args[3]:", args[3], "args[4]:", args[4], "args[5]:", args[5]))
netcdf.file <- args[1]
extract_point_or_area <- "AREA"

wrfout <- ncdf4::nc_open(netcdf.file)

xlon <- ncvar_get(wrfout, varid = 'XLONG')
xlat <- ncvar_get(wrfout, varid = 'XLAT')
rain <- ncvar_get(wrfout, varid = 'RAINNC')


# Default number of stations
stations_number = 1

# There are 6 stations
if (args[3] == 'ALL') {
  stations_number = 6
}

# Points data
st_coord_names <- c('CH', 'XA', 'JO', 'CN', 'CT', 'CA')
st_coord_i <- c(155, 167, 209, 226, 257, 238)
st_coord_j <- c(236, 243, 231, 218, 227, 250)


forecast_time <- as.numeric(args[4])+1
t_start=1
# forecast_time=25  # Forecast Time: 24h
# forecast_time=49  # Forecast Time: 48h
# forecast_time=73  # Forecast Time: 72h


#### OBSERVATIONAL data (PRP - precipitation) for all stations
#     - the 0000 UTC data will be excluded
#     - time range: from 2020/08/14;0100 UTC  to  2020/08/15;0000 UTC
st_CH_prp <- c(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 10, 5.8, 0.6, 1.4, 0.8, 0.0, 0.0, 0.2)
st_XA_prp <- c(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 8.4, 2.2, 0.6, 0.0, 0.0, 0.0, 0.0)

#st_JO_prp <- c(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, NA, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 24.6, 2.4, 0.2, 3, 0.6, 0.0)
st_JO_prp <- c(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 24.6, 2.4, 0.2, 3, 0.6, 0.0)
st_CN_prp <- c(0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.6, 10, 4.8, 1.6, 21.4, 0.2)

st_CA_prp <- c(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 3.8, 0.0, 0.0, 0.0, 0.0)
st_CT_prp <- c(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 19.4, 0.4, 0.2, 6.4)

#st_ALL_prp <- rbind(st_CH_prp, st_XA_prp, st_JO_prp, st_CN_prp, st_CA_prp, st_CT_prp)
st_ALL_prp <- c(st_CH_prp, st_XA_prp, st_JO_prp, st_CN_prp, st_CA_prp, st_CT_prp)

if (DEBUG){
  print(paste(" --- Parameters ---"))
  print(paste("WRF output filename (netcdf.file)", netcdf.file))
  print(paste("Type of summarization: ", extract_point_or_area))
  print(paste("Forecast time (forecast_time):", forecast_time))
  print(paste("Forecast time (t_start):", t_start))

}


#### FORECAST data (PRP and other)

## Extracting the variables from netcdf file (WRF output)
xlon <- ncvar_get(wrfout, varid = 'XLONG')
nlon <- dim(xlon)

xlat <-  ncvar_get(wrfout, varid = 'XLAT')
nlat <- dim(xlat)

print(c(nlon,nlat))

time <- ncvar_get(wrfout, "XTIME")
ntime <- dim(time)
head(time)
tunits <- ncatt_get(wrfout, "XTIME", "units")
tunits[["value"]]


# Timestamps in POSIX formats
cf <- CFtime(tunits$value, calendar="proleptic_gregorian", time) 
timestamps <- CFtimestamp(cf)
hours <- c(01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24)

# RAINNC:description = "ACCUMULATED TOTAL GRID SCALE PRECIPITATION"
rainnc <- ncvar_get(wrfout, varid = "RAINNC")
runits <- ncatt_get(wrfout, "RAINNC", "units")
runits[["value"]]
dim(rainnc)

# RAINC:description = "ACCUMULATED TOTAL CUMULUS PRECIPITATION"
rainc <- ncvar_get(wrfout, varid = "RAINC")
runits <- ncatt_get(wrfout, "RAINC", "units")
runits[["value"]]
dim(rainc)
nc_close(wrfout)


# For missing values in NetCDF files:
#  “fill values” (_FillValue) or missing values (missing_value)
# In R, we use NA for missing values:
#   rainnc[rainnc == fillvalue$value] <- NA
#   rainc[rainc == fillvalue$value] <- NA
# TODO: Erro: objeto 'fillvalue' não encontrado

# TODO Not used. It is used for image plotting
lon <- xlon[,1,]
dim(lon)
lat <- xlat[1,,]
dim(lat)


###  How the i and j coordinates (from WRF) are named and
###      refered in extraction and statistic calculations

# Nome e localização em termos de coordenadas WRF para os 25 pontos
#  Considerando o domínio da execução da conf B, cujo domínio D2 tem
#  resolução de 2km, daria uma área de 10x10km.

# pa pb pc pd pe
# pf pg ph pi pj
# pk pl pm pn po
# pp pq pr ps pt
# pu pv px pz py

# The matrix only contains DATA from WRF Forecast
# The index of the array (1-24) will be associated with forecast HOUR
prp_avg_area <- 0.0
prp_mean_area <- matrix(1:24, nrow = 24, ncol = 1)
#colnames(prp_mean_area) <- c("hour","prp_obs","prp_mean_area")
colnames(prp_mean_area) <- c("prp_mean_area")

# prp_mean_for_all_points <- matrix(1:144, nrow = 144, ncol = 1)
prp_mean_for_all_points <- c()

# Copy the Mean Error (bias) from all stations and generate a final plot
ME_for_st_CH <- matrix(1:24, nrow = 24, ncol = 1)
ME_for_st_XA <- matrix(1:24, nrow = 24, ncol = 1)
ME_for_st_JO <- matrix(1:24, nrow = 24, ncol = 1)
ME_for_st_CN <- matrix(1:24, nrow = 24, ncol = 1)
ME_for_st_CA <- matrix(1:24, nrow = 24, ncol = 1)
ME_for_st_CT <- matrix(1:24, nrow = 24, ncol = 1)

# To store the actual diffences for a final plot containing all stations
DIF_for_st_CH <- matrix(1:24, nrow = 24, ncol = 1)
DIF_for_st_XA <- matrix(1:24, nrow = 24, ncol = 1)
DIF_for_st_JO <- matrix(1:24, nrow = 24, ncol = 1)
DIF_for_st_CN <- matrix(1:24, nrow = 24, ncol = 1)
DIF_for_st_CA <- matrix(1:24, nrow = 24, ncol = 1)
DIF_for_st_CT <- matrix(1:24, nrow = 24, ncol = 1)

if (DEBUG){
  print(paste(" -------- Extracting Data and Collecting Statistics -------")) 
}

# st_coord_names <- c('CH', 'XA', 'JO', 'CN', 'CT', 'CA')
# st_coord_i <- c(155, 167, 209, 226, 257, 238)
# st_coord_j <- c(236, 243, 231, 218, 227, 250)

for (s in 1:stations_number) {
  st_name <- st_coord_names[s]
  i <- st_coord_i[s]
  j <- st_coord_j[s]
  if (DEBUG){
    print(paste("Coordinate i=x: ", i))
    print(paste("Coordinate j=y: ", j))
    print(paste("Name of INMET OBS station: ", st_name))
  }
  
### Loop for all time steps: extract data and calculate
###    statistics

  #  Compare OBS data time with WRF forecast at:
  #   t[2]  timestamps[2]  [1] "2020-08-14T01:00:00"
  #   t[25] timestamps[25] [1] "2020-08-15T00:00:00"
  for (t in (t_start+1):forecast_time){
    
    # pa: i-2,j+2
    r_pa <- rainnc[i-2,j+2,t]+rainc[i-2,j+2,t]-(rainnc[i-2,j+2,t-1]+rainc[i-2,j+2,t-1])
    # pb: i-1,j+2
    r_pb <- rainnc[i-1,j+2,t]+rainc[i-1,j+2,t]-(rainnc[i-1,j+2,t-1]+rainc[i-1,j+2,t-1])
    # pc: i,j+2
    r_pc <- rainnc[i,j+2,t]+rainc[i,j+2,t]-(rainnc[i,j+2,t-1]+rainc[i,j+2,t-1])
    # pd: i+1,j+2
    r_pd <- rainnc[i+1,j+2,t]+rainc[i+1,j+2,t]-(rainnc[i+1,j+2,t-1]+rainc[i+1,j+2,t-1])
    # pe: i+2,j+2
    r_pe <- rainnc[i+2,j+2,t]+rainc[i+2,j+2,t]-(rainnc[i+2,j+2,t-1]+rainc[i+2,j+2,t-1])
    
    # ----  pf pg ph pi pj
    # pf: i-2,j+1
    r_pf <- rainnc[i-2,j+1,t]+rainc[i-2,j+1,t]-(rainnc[i-2,j+1,t-1]+rainc[i-2,j+1,t-1])
    # pg: i-1,j+1
    r_pg <- rainnc[i-1,j+1,t]+rainc[i-1,j+1,t]-(rainnc[i-1,j+1,t-1]+rainc[i-1,j+1,t-1])
    # ph: i,j+1
    r_ph <- rainnc[i,j+1,t]+rainc[i,j+1,t]-(rainnc[i,j+1,t-1]+rainc[i,j+1,t-1])
    # pi: i+1,j+1
    r_pi <- rainnc[i+1,j+1,t]+rainc[i+1,j+1,t]-(rainnc[i+1,j+1,t-1]+rainc[i+1,j+1,t-1])
    # pj: i+2,j+1
    r_pj <- rainnc[i+2,j+1,t]+rainc[i+2,j+1,t]-(rainnc[i+2,j+1,t-1]+rainc[i+2,j+1,t-1])
    
    # ----  pk pl pm pn po
    # pk: i-2,j
    r_pk <- rainnc[i-2,j,t]+rainc[i-2,j,t]-(rainnc[i-2,j,t-1]+rainc[i-2,j,t-1])
    # pl: i-1,j
    r_pl <- rainnc[i-1,j,t]+rainc[i-1,j,t]-(rainnc[i-1,j,t-1]+rainc[i-1,j,t-1])
    # pm: i,j
    r_pm <- rainnc[i,j,t]+rainc[i,j,t]-(rainnc[i,j,t-1]+rainc[i,j,t-1])
    # pn: i+1,j
    r_pn <- rainnc[i+1,j,t]+rainc[i+1,j,t]-(rainnc[i+1,j,t-1]+rainc[i+1,j,t-1])
    # po: i+2,j
    r_po <- rainnc[i+2,j,t]+rainc[i+2,j,t]-(rainnc[i+2,j,t-1]+rainc[i+2,j,t-1])
    
    # ----  pp pq pr ps pt
    # pp: i-2,j-1
    r_pp <- rainnc[i-2,j-1,t]+rainc[i-2,j-1,t]-(rainnc[i-2,j-1,t-1]+rainc[i-2,j-1,t-1])
    # pq: i-1,j-1
    r_pq <- rainnc[i-1,j-1,t]+rainc[i-1,j-1,t]-(rainnc[i-1,j-1,t-1]+rainc[i-1,j-1,t-1])
    # pr: i,j-1
    r_pr <- rainnc[i,j-1,t]+rainc[i,j-1,t]-(rainnc[i,j-1,t-1]+rainc[i,j-1,t-1])
    # ps: i+1,j-1
    r_ps <- rainnc[i+1,j-1,t]+rainc[i+1,j-1,t]-(rainnc[i+1,j-1,t-1]+rainc[i+1,j-1,t-1])
    # pt: i+2,j-1
    r_pt <- rainnc[i+2,j-1,t]+rainc[i+2,j-1,t]-(rainnc[i+2,j-1,t-1]+rainc[i+2,j-1,t-1])
    
    # ----  pu pv px pz py
    # pu: i-2,j-1
    r_pu <- rainnc[i-2,j-2,t]+rainc[i-2,j-2,t]-(rainnc[i-2,j-2,t-1]+rainc[i-2,j-2,t-1])
    # pv: i-1,j-1
    r_pv <- rainnc[i-1,j-2,t]+rainc[i-1,j-2,t]-(rainnc[i-1,j-2,t-1]+rainc[i-1,j-2,t-1])
    # px: i,j-1
    r_px <- rainnc[i,j-2,t]+rainc[i,j-2,t]-(rainnc[i,j-2,t-1]+rainc[i,j-2,t-1])
    # pz: i+1,j-1
    r_pz <- rainnc[i+1,j-2,t]+rainc[i+1,j-2,t]-(rainnc[i+1,j-2,t-1]+rainc[i+1,j-2,t-1])
    # py: i+2,j-1
    r_py <- rainnc[i+2,j-2,t]+rainc[i+2,j-2,t]-(rainnc[i+2,j-2,t-1]+rainc[i+2,j-2,t-1])
    
    
    result <- c(r_pa, r_pb, r_pc, r_pd, r_pe, r_pf, r_pg, r_ph, r_pi, r_pj, r_pk, r_pl, r_pm, r_pn, r_po, r_pp, r_pq, r_pr, r_ps, r_pt, r_pu, r_pv, r_px, r_pz, r_py)
    # Remove missing values from calculus: na.rm=TRUE. If there were a missing value,
    #    then the function will end with a error.
    prp_avg_area <- mean(result, na.rm=TRUE)
    prp_mean_area[t-1] <- prp_avg_area
    
    if (DEBUG){
      print(result)
      print(paste("Time: ", timestamps[t], "t:", t, "  ", "prp_mean_area[t-1]:", prp_mean_area[t-1]))
    }
  }

  # ===== Concatenate all stations in one vector for statistics about all the area
  # Need convert MATRIX (prp_mean_area) to VECTOR: as.vector(), c()
  if (s == 1){
    prp_mean_for_all_points <- append(prp_mean_for_all_points, as.vector(prp_mean_area), 1)
  } else{
    prp_mean_for_all_points <-append(prp_mean_for_all_points, c(prp_mean_area), ((s-1)*24)+1)
  }
  if (DEBUG){
    print(paste("Station:", st_name, "prp_mean_for_all_points: ", prp_mean_for_all_points))
  }
  
  if (st_name == 'CH') {
    prp_obs_from_st <- as.vector(st_CH_prp)
  } else if (st_name == 'XA') {
    prp_obs_from_st <- as.vector(st_XA_prp)
  } else if (st_name == 'JO') {
    prp_obs_from_st <- as.vector(st_JO_prp)
  } else if (st_name == 'CN') {
    prp_obs_from_st <- as.vector(st_CN_prp)
  }else if (st_name == 'CA') {
    prp_obs_from_st <- as.vector(st_CA_prp)
  }else if (st_name == 'CT') {
    prp_obs_from_st <- as.vector(st_CT_prp)
  }
  if (DEBUG){
    print(paste("PRP OBS from ", st_name, "=", "prp_obs_from_st: ", prp_obs_from_st))
    print(paste("prp_mean_area: ", prp_mean_area))
  }
  
  #######################################################################
  # RMSE is optimal for normal (Gaussian) errors,
  #    and MAE is optimal for Laplacian errors. 
  # ===========   Statisticas -> Mean Absolute Error (F-O)  =============

  # ======= MAE (Mean Absolute Error): (F)orecast (mean Area)   ============
  # Matrix for MAE (Mean Absolute Error)
  # The index of the array (1-24) will be associated with forecast HOUR
  
  MAE_for_prp_area <- matrix(1:24, nrow = 24, ncol = 1)
  colnames(MAE_for_prp_area) <- c("mae_area_time")
  
  MAE_for_station = 0
  for (t in t_start:(forecast_time-1)){
    MAE_for_prp_area[t] <- abs(prp_mean_area[t] - prp_obs_from_st[t])
    MAE_for_station = MAE_for_prp_area[t] + MAE_for_station
  }
  MAE_for_station = MAE_for_station / forecast_time
  if (DEBUG){
    print(paste("Station:", st_name, "MAE_for_prp_area: ", MAE_for_prp_area))
  }
  
  
  
  # ======= Difference between Forecast and Observed  ============
 
  DIF_for_prp_area <- matrix(1:24, nrow = 24, ncol = 1)
  colnames(DIF_for_prp_area) <- c("dif_area_time")
  
  for (t in t_start:(forecast_time-1)){
    DIF_for_prp_area[t] <- (prp_mean_area[t] - prp_obs_from_st[t])
  }

  if (DEBUG){
    print(paste("DIF_for_prp_area_time: ", DIF_for_prp_area))
  }

  
  # For PRP, the ratio is calculated as ME = F/O  (\cite{stull2017practical}
  # for (t in t_start:(forecast_time-1)){
  #  DIF_for_prp_area_div[t] <- (prp_mean_area[t] / prp_obs_from_st[t])
  #}
  #if (DEBUG){
  #  print(paste("Station:", st_name, "DIF_for_prp_area_div: ", DIF_for_prp_area_div))
  #}                                                                              

  
  # ======= Absolute Error between Forecast and Observed  ============
  
  AE_for_prp_area <- matrix(1:24, nrow = 24, ncol = 1)
  colnames(AE_for_prp_area) <- c("ae_area_time")
  
  for (t in t_start:(forecast_time-1)){
    AE_for_prp_area[t] <- abs(prp_mean_area[t] - prp_obs_from_st[t])
  }
  AE_from_metrics <- ae(prp_obs_from_st, prp_mean_area)
  
  if (DEBUG){
    print(paste("AE_for_prp_area_time: ", AE_for_prp_area))
    print(paste("AE_from_metrics: ", AE_from_metrics))
  }


  
  # ======= RMSE: (F)orecast (mean Area and Time)  ============
  # Root mean squared error (RMSE)
  
  RMSE_for_prp_area <- matrix(1:24, nrow = 24, ncol = 1)
  colnames(RMSE_for_prp_area) <- c("rmse_area_time")
  
  for (t in t_start:(forecast_time-1)){
    RMSE_for_prp_area[t] <- sqrt(mean((prp_mean_area[t] - prp_obs_from_st[t])^2))
  }
  if (DEBUG){
    print(paste("Station:", st_name, "RMSE_for_prp_area: ", RMSE_for_prp_area))
  }
  # RMSE
  # sqrt(mean((data$actual - data$predicted)^2))
  

  
  ##  Processing statistics PER station
  # ==== Statistics from Package Metrics: generate unique values
  # https://cran.r-project.org/web/packages/Metrics/Metrics.pdf
  AE_for_station <- ae(prp_obs_from_st, prp_mean_area)
  BIAS_for_station <- bias(prp_obs_from_st, prp_mean_area)
  MAE_for_station <- mae(prp_obs_from_st, prp_mean_area)
  RMSE_for_station <- rmse(prp_obs_from_st, prp_mean_area)
  
  print(paste("Station:", st_name, "  AE:", AE_for_station, "  BIAS:", BIAS_for_station, "   MAE:", MAE_for_station, " RMSE:", RMSE_for_station))
  
  # ===========    Writing SUMMARY STATS PER STATION to CSV file   ============
  data2 <- data.frame(BIAS_for_station, MAE_for_station, RMSE_for_station)
  csvfilename <- paste(args[2], "-", st_name, "-summary-stats.csv", sep="")
  write.table(data2, csvfilename, row.names=FALSE, sep=",")
  print(paste("Writing -> write.csv2(data2,file=csvfilename, row.names = TRUE)"))

  # ====     Writing MEAN data PER TIME and PER STATION to CSV file    =======
  
  #data <- data.frame(timestamps[2:25], prp_obs_from_st, prp_mean_area, DIF_for_prp_area, AE_for_prp_area, MAE_for_prp_area, RMSE_for_prp_area)
  data <- data.frame(timestamps[2:25], prp_obs_from_st, prp_mean_area, DIF_for_prp_area, AE_for_prp_area)
  csvfilename <- paste(args[2], "-", st_name, "-prp-area-time-and-stats.csv", sep="")
  write.table(data, csvfilename, row.names=TRUE, sep=",")
  print(paste("Writing -> write.csv2(data,file=csvfilename, row.names = TRUE)"))

  
  if (st_name == "CH"){
    DIF_for_st_CH <- DIF_for_prp_area
  } else if (st_name == "XA"){
    DIF_for_st_XA <- DIF_for_prp_area
  } else if (st_name == "JO"){
    DIF_for_st_JO <- DIF_for_prp_area
  } else if (st_name == "CN"){
    DIF_for_st_CN <- DIF_for_prp_area
  } else if (st_name == "CA"){
    DIF_for_st_CA <- DIF_for_prp_area
  } else if (st_name == "CT"){
    DIF_for_st_CT <- DIF_for_prp_area
  }

  if (st_name == 'CH') {
    prp_obs_from_st <- as.vector(st_CH_prp)
  } else if (st_name == 'XA') {
    prp_obs_from_st <- as.vector(st_XA_prp)
  } else if (st_name == 'JO') {
    prp_obs_from_st <- as.vector(st_JO_prp)
  } else if (st_name == 'CN') {
    prp_obs_from_st <- as.vector(st_CN_prp)
  }else if (st_name == 'CA') {
    prp_obs_from_st <- as.vector(st_CA_prp)
  }else if (st_name == 'CT') {
    prp_obs_from_st <- as.vector(st_CT_prp)
  }
  if (DEBUG){
    print(paste("--- Final Processing Station:", st_name, " with s: ", s))
  }  
  
}
################# Processing: FINISH ####################
########################################################



########################################################
###### Saving the statistics to files CSV:  FINISH #####

#  Plot of Quantitative Difference between Precipitation:
#   DIF =  Forecast - Observation
#  These commands plot 6 graphics (for 6 stations) on the same PDF page

#  svg(filename = paste0(i, ".svg")

# TODO TODO for error correction
# The config for pdf generate a PNG with error. Without config (as below),
#   the R plots all the images in same PDF page (filename: R)

plotfilename <- paste(args[2], "-ALL_st", "-dif-For-Obs.pdf", sep="")
print(paste("Filename for plot Difference (F-O): ", plotfilename))

#pdf.options(onefile=TRUE, paper="a4", pagecentre=TRUE)
pdf(file=plotfilename)
#title_for_plot <- paste("Diferença entre Previsto-Obs\n para ", st_name)
par(mfrow=c(3,2))
plot(hours, DIF_for_st_CH, type='b', ylim=c(-25,25), main="Dif. PRP (Prev-Obs) -Chapecó", xlab="Horas Prev", ylab="Dif. (mm)")
plot(hours, DIF_for_st_XA, type='b', ylim=c(-25,25), main="Dif. PRP (Prev-Obs) - Xanxerê", xlab="Horas Prev", ylab="Dif. (mm)") 
plot(hours, DIF_for_st_JO, type='b', ylim=c(-25,25), main="Dif. PRP (Prev-Obs) - Joaçaba", xlab="Horas Prev", ylab="Dif. (mm)") 
plot(hours, DIF_for_st_CN, type='b', ylim=c(-25,25), main="Dif. PRP (Prev-Obs) - Campos Novos", xlab="Horas Prev", ylab="Dif. (mm)") 
plot(hours, DIF_for_st_CA, type='b', ylim=c(-25,25), main="Dif. PRP (Prev-Obs) - Caçador", xlab="Horas Prev", ylab="Dif. (mm)")
plot(hours, DIF_for_st_CT, type='b', ylim=c(-25,25), main="Dif. PRP (Prev-Obs) - Curitibanos", xlab="Horas Prev", ylab="Dif. (mm)") 

dev.off()


#######################################################################

print(paste("st_ALL_prp: ", class(st_ALL_prp), length(st_ALL_prp)))
print(paste("prp_mean_for_all_points: ", class(prp_mean_for_all_points), length(prp_mean_for_all_points)))
rmse_for_all_st <- rmse(st_ALL_prp, prp_mean_for_all_points)
print(paste("RMSE:", rmse_for_all_st))


bias_for_all_st <- bias(st_ALL_prp, prp_mean_for_all_points)
print(paste("BIAS:", bias_for_all_st))

mae_for_all_st <- mae(st_ALL_prp, prp_mean_for_all_points)
print(paste("MAE:", mae_for_all_st))

csvfilename <- paste(args[2],"-summary-stats.csv",sep="")
df1 <- data.frame(mae_for_all_st)
colnames(df1) <- c("MAE")
df2 <- data.frame(bias_for_all_st)
colnames(df2) <- c("BIAS")
df3 <- data.frame(rmse_for_all_st)
colnames(df1) <- c("RMSE")

data <- data.frame(mae_for_all_st, bias_for_all_st, rmse_for_all_st)
colnames(data) <- c("MAE", "BIAS", "RMSE")
#write.csv2(rbind(df1,df2,df3), file=filename_output, row.names = FALSE)
write.table(data, csvfilename, row.names=TRUE, sep=",")

